import { relative, sep } from 'node:path';
import type { Manifest, ManifestChunk } from 'vite';
import { diagnostic } from './config.js';

export const HOT_RELOAD_CLIENT = 'virtual:shopify-theme-hot-reload';
export const RESOLVED_HOT_RELOAD_CLIENT = `\0${HOT_RELOAD_CLIENT}`;
const HOT_RELOAD_CLIENT_PATH = `/@id/__x00__${HOT_RELOAD_CLIENT}`;
export const HOT_RELOAD_EVENT = 'shopify:theme-update';
const STYLE_ENTRY_RE = /\.(?:css|scss|sass|less|styl|stylus)$/i;
export const HOT_RELOAD_SOURCE = `const reloadKey = 'vite-plugin-shopify-theme:reload';
const reloadDelay = 1000;
const pendingReload = Number(sessionStorage.getItem(reloadKey));
if (pendingReload) {
  sessionStorage.removeItem(reloadKey);
  setTimeout(() => window.location.reload(), Math.max(0, reloadDelay - (Date.now() - pendingReload)));
}
if (import.meta.hot) {
  const rememberReload = () => sessionStorage.setItem(reloadKey, String(Date.now()));
  import.meta.hot.on('vite:beforeFullReload', rememberReload);
  import.meta.hot.on('${HOT_RELOAD_EVENT}', () => {
    rememberReload();
    window.location.reload();
  });
}
`;

export function sourceKey(path: string, root: string): string { return relative(root, path).split(sep).join('/'); }

export interface ManifestTags { preloads: string[]; styles: string[]; scripts: string[] }

export function collectManifestTags(manifest: Manifest, entrySources: string[]): ManifestTags {
  const preloads: string[] = []; const styles: string[] = []; const scripts: string[] = [];
  const seenImports = new Set<string>(); const seenCss = new Set<string>(); const seenScripts = new Set<string>();
  const addStyles = (chunk: ManifestChunk): void => {
    if (chunk.file.endsWith('.css') && !seenCss.has(chunk.file)) { seenCss.add(chunk.file); styles.push(chunk.file); }
    for (const css of chunk.css ?? []) if (!seenCss.has(css)) { seenCss.add(css); styles.push(css); }
  };
  const visitImports = (key: string): void => {
    const chunk = manifest[key];
    if (!chunk) throw diagnostic(`Vite manifest is missing declared entry "${key}". Confirm that plugin-owned top-level input is not overridden and run a clean build.`);
    for (const imported of chunk.imports ?? []) if (!seenImports.has(imported)) {
      seenImports.add(imported);
      const importedChunk = manifest[imported];
      if (!importedChunk) throw diagnostic(`Vite manifest entry "${key}" references missing imported chunk "${imported}". Run a clean build and retry.`);
      visitImports(imported); addStyles(importedChunk);
      if (importedChunk.file.endsWith('.js')) preloads.push(importedChunk.file);
    }
  };
  for (const source of entrySources) {
    const chunk = manifest[source];
    if (!chunk) throw diagnostic(`Vite manifest is missing declared entry "${source}". Confirm that plugin-owned top-level input is not overridden and run a clean build.`);
    addStyles(chunk); visitImports(source);
    if (!seenScripts.has(chunk.file)) { seenScripts.add(chunk.file); scripts.push(chunk.file); }
  }
  return { preloads, styles, scripts };
}

const asset = (file: string) => `{{ '${file.replaceAll("'", "\\'")}' | asset_url }}`;

export function productionSnippet(manifest: Manifest, entries: Record<string, string>, root: string): string {
  const blocks = Object.entries(entries).map(([name, path]) => {
    const tags = collectManifestTags(manifest, [sourceKey(path, root)]);
    const lines = [...tags.styles.map((f) => `<link rel="stylesheet" href="${asset(f)}">`), ...tags.scripts.filter((f) => f.endsWith('.js')).map((f) => `<script type="module" src="${asset(f)}"></script>`), ...tags.preloads.map((f) => `<link rel="modulepreload" href="${asset(f)}">`)];
    return `{% when '${name}' %}\n${lines.join('\n')}`;
  });
  return `{% comment %} Generated by vite-plugin-shopify-theme. Do not edit. {% endcomment %}\n{% case entry %}\n${blocks.join('\n')}\n{% endcase %}\n`;
}

export function developmentSnippet(origin: string, entries: Record<string, string>, root: string): string {
  const blocks = Object.entries(entries).map(([name, path]) => {
    const url = `${origin}/${sourceKey(path, root)}`;
    const tag = STYLE_ENTRY_RE.test(path) ? `<link rel="stylesheet" href="${url}" crossorigin="anonymous">` : `<script type="module" src="${url}" crossorigin="anonymous"></script>`;
    return `{% when '${name}' %}\n${tag}`;
  });
  return `{% comment %} Temporary development file generated by vite-plugin-shopify-theme. {% endcomment %}\n{% if entry == blank %}\n<script type="module" src="${origin}/@vite/client" crossorigin="anonymous"></script>\n<script type="module" src="${origin}${HOT_RELOAD_CLIENT_PATH}" crossorigin="anonymous"></script>\n{% else %}\n{% case entry %}\n${blocks.join('\n')}\n{% endcase %}\n{% endif %}\n`;
}
